name: Nothing Firmware Dumper

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'URLs (comma or space separated)'
        required: true
      name:
        description: 'Release tag'
        required: true

jobs:
  dump:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup environment
      run: |
        sudo apt update
        sudo apt -y install aria2 zstd p7zip-full parallel openssl xxhash
        python3 -m pip install gdown

    - name: Set script permissions
      run: chmod +x dump.sh

    - name: Download & Process OTA Packages
      id: dump
      run: |
        echo "release_tag=${{ inputs.name }}" >> "$GITHUB_ENV"
        IFS=',' read -ra URLS <<< "${{ inputs.urls }}"
        for url in "${URLS[@]}"; do
          echo "$url"
        done | xargs ./dump.sh

    - name: Upload release assets
      uses: ncipollo/release-action@v1
      with:
        artifacts: out/*
        artifactErrorsFailBuild: true
        tag: ${{ env.release_tag }}
        name: ${{ steps.dump.outputs.release_name }}
        body: ${{ steps.dump.outputs.body }}
        token: ${{ secrets.GITHUB_TOKEN }}
